### ISSUE TITLE
ProgX Sensors flipping between known and unknown

### ISSUE THREAD

**Issue by ASomerN** [kellerza/sunsynk#78] opened 2022-12-16 17:03 UTC
### Issue related to

Sunsynk ProgX Sensors flipping between known and unknown

### Describe the issue/bug

I can write the values for ProgX times and set:

- No Grid or Gen
- Allow Grid
- Allow Gen
- Allow Gen & Grid

But on setting update values, other values as implemented in the example Home Assistant vertical stack flip to unknown where previously they may have been known.

For example, currently Prog5 Time is unknown:

![image](https://user-images.githubusercontent.com/29146770/208147959-53baa3ae-36f6-4bf5-8ea7-55a92a820836.png)

When I set Prog5 it correctly updates the inverter settings (i check in the inverter and the app) but then another sensor becomes unknown:

![image](https://user-images.githubusercontent.com/29146770/208148396-80664636-ecee-4d86-b7eb-171b577c4067.png)

```
PORT: /dev/ttyUSB0
DEVICE: /dev/ttyUSB0
DRIVER: pymodbus
SUNSYNK_ID: "*"
SENSOR_PREFIX: sunsynk_
SENSORS:
  - total_pv_power
  - total_battery_charge
  - total_battery_discharge
  - total_grid_export
  - total_grid_import
  - battery_soc
  - grid_power
  - pv1_power
  - pv2_power
  - battery_power
  - load_power
  - grid_frequency
  - control_mode
  - priority_mode
  - prog1_time
  - prog2_time
  - prog3_time
  - prog4_time
  - prog5_time
  - prog6_time
  - prog1_power
  - prog2_power
  - prog3_power
  - prog4_power
  - prog5_power
  - prog6_power
  - prog1_capacity
  - prog2_capacity
  - prog3_capacity
  - prog4_capacity
  - prog5_capacity
  - prog6_capacity
  - prog1_charge
  - prog2_charge
  - prog3_charge
  - prog4_charge
  - prog5_charge
  - prog6_charge
READ_SENSORS_BATCH_SIZE: 60
NUMBER_ENTITY_MODE: auto
PROFILES:
  - system_mode
MODBUS_SERVER_ID: 1
MQTT_HOST: core-mosquitto
MQTT_PORT: 1883
MQTT_USERNAME: *
MQTT_PASSWORD: *
DEBUG: 0

```

**Expected behavior**

Sensors that were previously known would not become unknown when a different sensor is changed.
Ideally, on initialization all requested sensors would be known

### Your environment

- Home Assistant version: 2022.12.6
- Addon version:  2022.11.29-0.2.5
- Inverter make: Sunsynk 
- Inverter Model:  8.8kw
- Inverter Firmware: COMM: e424 - MCU:5373

### Logs

Logs on start

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2022-12-16 16:59:30,071 INFO    Loading HASS OS configuration
2022-12-16 16:59:30,188 INFO    ############################################################
2022-12-16 16:59:30,188 INFO        Sensor deprecated: total_pv_power -> total_pv_energy
2022-12-16 16:59:30,189 INFO    ############################################################
2022-12-16 16:59:30,190 INFO    Added hidden sensor battery_low_capacity as other sensors depend on it
2022-12-16 16:59:30,191 INFO    Filter *last used for battery_soc, total_battery_charge, total_battery_discharge, total_grid_export, total_grid_import, total_pv_power
2022-12-16 16:59:30,191 INFO    Filter *step used for battery_power, control_mode, grid_frequency, grid_power, load_power, pv1_power, pv2_power
2022-12-16 16:59:30,191 INFO    Filter *round_robin used for priority_mode, prog1_capacity, prog1_charge, prog1_power, prog1_time, prog2_capacity, prog2_charge, prog2_power, prog2_time, prog3_capacity, prog3_charge, prog3_power, prog3_time, prog4_capacity, prog4_charge, prog4_power, prog4_time, prog5_capacity, prog5_charge, prog5_power, prog5_time, prog6_capacity, prog6_charge, prog6_charge, prog6_power, prog6_time
2022-12-16 16:59:30,203 INFO    Protocol made connection.
2022-12-16 16:59:30,204 INFO    Connected to /dev/ttyUSB0
2022-12-16 16:59:30,205 INFO    Reading startup sensors rated_power, prog6_time, prog3_time, prog5_time, battery_low_capacity, prog2_time, prog4_time, serial, prog1_time
2022-12-16 16:59:30,403 INFO    ############################################################
2022-12-16 16:59:30,403 INFO                Inverter serial number '*'
2022-12-16 16:59:30,403 INFO    ############################################################
2022-12-16 16:59:30,408 INFO    MQTT: Connecting to homeassistant@core-mosquitto:1883
2022-12-16 16:59:31,312 INFO    MQTT: Connection successful
```

After subsequently editing a sensor, it updates but another becomes unknown:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2022-12-16 16:59:30,071 INFO    Loading HASS OS configuration
2022-12-16 16:59:30,188 INFO    ############################################################
2022-12-16 16:59:30,188 INFO        Sensor deprecated: total_pv_power -> total_pv_energy
2022-12-16 16:59:30,189 INFO    ############################################################
2022-12-16 16:59:30,190 INFO    Added hidden sensor battery_low_capacity as other sensors depend on it
2022-12-16 16:59:30,191 INFO    Filter *last used for battery_soc, total_battery_charge, total_battery_discharge, total_grid_export, total_grid_import, total_pv_power
2022-12-16 16:59:30,191 INFO    Filter *step used for battery_power, control_mode, grid_frequency, grid_power, load_power, pv1_power, pv2_power
2022-12-16 16:59:30,191 INFO    Filter *round_robin used for priority_mode, prog1_capacity, prog1_charge, prog1_power, prog1_time, prog2_capacity, prog2_charge, prog2_power, prog2_time, prog3_capacity, prog3_charge, prog3_power, prog3_time, prog4_capacity, prog4_charge, prog4_power, prog4_time, prog5_capacity, prog5_charge, prog5_power, prog5_time, prog6_capacity, prog6_charge, prog6_charge, prog6_power, prog6_time
2022-12-16 16:59:30,203 INFO    Protocol made connection.
2022-12-16 16:59:30,204 INFO    Connected to /dev/ttyUSB0
2022-12-16 16:59:30,205 INFO    Reading startup sensors rated_power, prog6_time, prog3_time, prog5_time, battery_low_capacity, prog2_time, prog4_time, serial, prog1_time
2022-12-16 16:59:30,403 INFO    ############################################################
2022-12-16 16:59:30,403 INFO                Inverter serial number '*'
2022-12-16 16:59:30,403 INFO    ############################################################
2022-12-16 16:59:30,408 INFO    MQTT: Connecting to homeassistant@core-mosquitto:1883
2022-12-16 16:59:31,312 INFO    MQTT: Connection successful
2022-12-16 17:01:00,090 INFO    Writing sensor Prog5 Time: prog5_time=(1720,)  [old (1705,)]
```

**Comment by Ivan-L** [comment] 2022-12-30 09:27
Hi @ASomerN, I see @kellerza issued an update which causes the `retain` flag to be set for R/W sensors, which is awesome. If that does not solve your issue would you mind increasing the verbosity of the logs as the more verbose logs might provide a clue as to why the value of "Unknown" is being set? I am thinking perhaps your inverter (perhaps after a firmware update) is providing values other than 4/5/6/7 [here](https://github.com/kellerza/sunsynk/blob/0acbd110d107826aab18eb1d603705c7a071bfc6/sunsynk/definitions.py#L230-L235).
```python
PROG_CHARGE_OPTIONS = {
    4: "No Grid or Gen",
    5: "Allow Grid",
    6: "Allow Gen",
    7: "Allow Grid & Gen",
}
```
That those registers are not documented very well, so it may well be that there are extra bits set that we do not know about.

**Comment by kellerza** [comment] 2022-12-30 13:44
The unknown state (at least for the progx_time sensors) seems to be a bug in the HASS Select auto-discovery. Refer to https://github.com/home-assistant/core/issues/84844

You will notice it's always the previous and next time that gets updated and loses its value

**Comment by kellerza** [comment] 2022-12-30 13:46
For the unknown you see with the charge options (grid/no-grid) it's related to #72

**Comment by kellerza** [comment] 2022-12-30 13:49
@Ivan-L it might be when you originally implemented this feature this bug did not exist in HASS, but it's definitely not working on my latest HASS install, as per the bug I filed above.

Setting the time is not something I've really used before, until I got an additional battery this week 😉

**Comment by Ivan-L** [comment] 2022-12-30 18:47
Thanks @kellerza, I've just read through the issue you filed and your description makes absolute sense. You are right, this does look like a bug where updating an MQTT select's options causes the state of the select to become unknown which bug didn't exist at the time of implementation. In fact I recently changed some ProgN...Time sensor values, perhaps a few weeks back and this bug did not show up, so perhaps it is the latest HASS install, like you said. Since the ProgN..Time sensors depend on each other, it explains why when changing one the other selects lose their value due to the bug, since their options are updated.

However, this would apply just for the ProgN..Time sensors since they have dependencies and their select options are updated when the dependencies change. ProgN..Charge sensors do not get their options updated after being created for the first time. I regularly update ProgN..Charge sensors before load shedding depending on the state of the battery when I quickly want to charge from the grid and did not experience the bug, though like you I rarely change the ProgN..Time sensors and can confirm that they do suffer from this bug on my side too after testing today.

So then we have two issues:
- A recently introduced bug in HASS as per the issue you filed there which causes the ProgN...Time sensors to lose their state when their options are updated
- A potentially separate issue where the bits of the ProgN..Charge register values need to be looked at more closely. Because @ASomerN in this issue is using a Sunsynk 8(.8?)kW inverter, unlike the Turbo Energy inverter mentioned in #72, it would be good to get the old/new values from the logs of @ASomerN when ProgN..Charge values are changed from "Unknown" to a known value through HASS. Alternatively, perhaps the reason for @ASomerN's "Unknown" values for the ProgN..Charge sensors in the screenshot in this issue are due to a HASS restart without an add-on restart, which would cause the "Unknown" values - which should have been fixed by your latest `retain` update. I haven't tested `retain` update for myself yet because I'm running a local copy of the add-on with some extra updates that I haven't PRed yet. If your update fixes @ASomerN's "Unknown" values for the ProgN..Charge sensors then that is good news - it is then only the Turbo Charge inverters which have different register values for the ProgN..Charge sensors.

**Comment by duanemck** [comment] 2023-01-09 12:27
I'm seeing similar "UNKNOWN"s on my instance.
I have a Sunsynk 5kW inverter. I haven't tried writing any changes to the inverter yet, but it hasn't managed to read the values either. I see this in the logs quite a bit (white seems to be caused by an incoming MQTT message):

`Invalid option for select.sunsynk_prog2_charge: 'Unknown 3' (valid options: ['No Grid or Gen', 'Allow Grid', 'Allow Gen', 'Allow Grid & Gen'])` 

![image](https://user-images.githubusercontent.com/429394/211307763-d3ede6da-3b38-426e-9cd1-673c11b400cf.png)

**Comment by duanemck** [comment] 2023-01-09 12:29
Looking at the MQTT logs, it seems the "Unknown 3" is coming from there
![image](https://user-images.githubusercontent.com/429394/211308134-b2e9a44e-7531-4c65-907e-8b158e049d5b.png)

**Comment by jacekowski** [comment] 2023-01-10 14:28
I've just created pull request that should fix this,
registers in questions are actually used as individual bits, where bit 0 is grid charge, 1 is generator charge, 2, 3 and 4 are some sort of "GU" "BU" and "CH" modes.

**Comment by duanemck** [comment] 2023-01-10 14:51
> I've just created pull request that should fix this, registers in questions are actually used as individual bits, where bit 0 is grid charge, 1 is generator charge, 2, 3 and 4 are some sort of "GU" "BU" and "CH" modes.
> 
> Ideally those should be somehow split so both parts can be controlled independently.

Great, thank you, I'll keep an eye on the PR and update when it's merged.

**Comment by Ivan-L** [comment] 2023-01-10 15:33
I don’t think the register should be changed in that way because the current values do work.
Maybe check #72 where we had a discussion about this. My view is that we should introduce two new sensors for grid charge and gen charge which deal exclusively with bits 1 and 2 and do not touch the other bits. That should work for everyone.

**Comment by jacekowski** [comment] 2023-01-10 15:53
Possibly 2 sensors, 1 dealing with bits 0 and 1 (grid and gen charge) and then another one for mode selection (bits 2,3,4)

**Comment by Ivan-L** [comment] 2023-01-10 15:59
Yes exactly, or three sensors in total, one dealing with bit 1 only, another dealing with bit 2 only, and then the third dealing with the mode selection. The first two sensors could be switch entities.

**Closed** 2023-01-12 19:28 UTC
